source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'Functional.m', '~> 1.0'

# Add Kiwi as an exclusive dependency for the Test target
target :SampleAppWithCocoapodsTests, :exclusive => true do
  pod 'Kiwi'
end

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
